from typing import Any, Iterable, Protocol
from uuid import UUID

from base_api.modules.user.models import User


class UserRepository(Protocol):
    def get_all(self) -> Iterable[User]: ...
    def get_by_id(self, id: UUID) -> User | None: ...
    def create(self, data: User) -> User: ...
    def update(self, data: dict[str, Any]) -> User: ...
    def delete(self) -> None: ...
