from typing import Any, Iterable, Protocol
from uuid import UUID

from base_api.modules.user.models import User


class UserRepository(Protocol):
    async def get_all(self) -> Iterable[User]: ...
    async def get_by_id(self, id: UUID) -> User | None: ...
    async def get_by_login(self, login: str) -> User | None: ...
    async def create(self, data: User) -> User: ...
    async def update(self, data: dict[str, Any]) -> User: ...
    async def delete(self) -> None: ...
